[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core", "cheerio"]

[functions.scrape]
  memory = 3008
  timeout = 26

[functions.sheet-pricing]
  memory = 3008
  timeout = 26

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
