# Netlify configuration file

[build]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR_RENDER_APP_URL.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
